defmodule Emisar.Repo.Migrations.AutoGeneratedApiKeys do
  use Ecto.Migration

  @moduledoc """
  Mirrors the runner_auth_keys auto-generated pattern for api_keys: a
  fresh API key is minted on every Agents page load so the
  operator can copy the snippet without clicking "Generate". Auto-
  generated keys are invisible in operator-facing lists until an LLM
  actually makes its first MCP call (`api_keys.last_used_at` set, flag
  cleared). A per-account ring of 42 unused entries keeps DB churn
  bounded; eviction runs inside the same mint transaction.
  """

  def change do
    alter table(:api_keys) do
      add :auto_generated_at, :utc_datetime_usec
    end

    # Partial index supports the ring-eviction scan (account_id + age)
    # and the visibility filter (hide auto-generated + never-used).
    create index(:api_keys, [:account_id, :auto_generated_at],
             where: "auto_generated_at IS NOT NULL AND last_used_at IS NULL",
             name: :api_keys_auto_unused_idx
           )
  end
end
