defmodule Emisar.Repo.Migrations.AutoGeneratedInstallKeys do
  use Ecto.Migration

  @moduledoc """
  Adds the `auto_generated_at` flag to runner_auth_keys so the dashboard
  can mint a fresh install key on every page load without spamming the
  UI lists (auto-generated unused keys are hidden everywhere) or the
  DB (a per-account ring caps unused autos at 42; the eviction query
  runs inside the same mint transaction).

  A key transitions out of the auto-generated state the moment a runner
  registers with it — at which point it becomes a normal, visible,
  permanent auth key.
  """

  def change do
    alter table(:runner_auth_keys) do
      add :auto_generated_at, :utc_datetime_usec
    end

    # Supports the ring-eviction query (per-account scan + age order) and
    # the visibility filter (hide auto-generated + never-used). Partial
    # so manually-issued keys don't bloat the index.
    create index(:runner_auth_keys, [:account_id, :auto_generated_at],
             where: "auto_generated_at IS NOT NULL AND last_used_at IS NULL",
             name: :runner_auth_keys_auto_unused_idx
           )
  end
end
