# DNSSEC keys are read back from the zone so we can print the DS record to submit
# at the registrar. Empty until the zone's keys generate (first apply).
data "google_dns_keys" "emisar" {
  managed_zone = google_dns_managed_zone.emisar.id
}

output "lb_ipv4" {
  description = "Global anycast IPv4 of the HTTPS load balancer (the apex A record points here)."
  value       = google_compute_global_address.ipv4.address
}

output "lb_ipv6" {
  description = "Global anycast IPv6 of the HTTPS load balancer (the apex AAAA record points here)."
  value       = google_compute_global_address.ipv6.address
}

output "url" {
  description = "Public URL once DNS resolves and the managed cert provisions."
  value       = "https://${var.domain}"
}

output "container_image" {
  description = "Public GHCR image the MIG runs — publish it there before apply."
  value       = var.container_image
}

output "db_private_ip" {
  description = "Cloud SQL private IP (the DATABASE_URL secret is built from this)."
  value       = google_sql_database_instance.emisar.private_ip_address
}

output "nameservers" {
  description = "Set these as emisar.dev's NS records at the registrar (GoDaddy) to delegate DNS to Cloud DNS."
  value       = google_dns_managed_zone.emisar.name_servers
}

output "dnssec_ds_record" {
  description = "DS record to add at the registrar to complete DNSSEC. Do it LAST, after NS delegation resolves."
  value       = try(data.google_dns_keys.emisar.key_signing_keys[0].ds_record, "(pending — re-run after the zone's keys generate)")
}

output "pack_registry_bucket" {
  description = "GCS bucket holding the published pack-registry artifacts (the publisher and portal write/read here)."
  value       = google_storage_bucket.pack_registry.name
}

output "pack_registry_base_url" {
  description = "Public HTTPS base URL for pack artifacts — install snippets and the portal catalog loader join paths onto this (e.g. <base>/v1/catalog.json)."
  value       = "https://storage.googleapis.com/${google_storage_bucket.pack_registry.name}"
}

output "next_steps" {
  description = "One-time steps to bring the GCP stack up (nothing is applied by preparing this code)."
  value       = <<-EOT
    1. Terraform Cloud (org Dryga → project emisar → workspace emisar): set the
       workspace variables — GCP credentials (GOOGLE_CREDENTIALS env var, or dynamic
       WIF creds), and the SENSITIVE secret vars: paddle_api_key / paddle_webhook_secret /
       paddle_client_token (or disable_billing = true), postmark_api_token, and
       optionally postmark_webhook_secret / sentry_dsn / mixpanel_token.
       SECRET_KEY_BASE and the DB password are generated by the apply — nothing to set.
    2. Publish the portal image to public GHCR as ${var.container_image}
       (self-hosters pull the same artifact; pin a digest for reproducible rollouts).
    3. terraform apply (creates the VPC, Cloud SQL, MIG, LB, cert, and DNS zone).
    4. Delegate the domain — set these NS at the registrar:
         ${join("\n         ", google_dns_managed_zone.emisar.name_servers)}
    5. After NS resolves + the managed cert is ACTIVE, publish the DNSSEC DS at the registrar:
         terraform output dnssec_ds_record
       then GET https://${var.domain}/healthz should return 200 and `dig +dnssec ${var.domain}` shows the AD flag.
  EOT
}
