import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :emisar_web, EmisarWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force HTTPS in production (this also sets the HSTS header). Phoenix 1.8
  # reads `:force_ssl` via `Application.compile_env`, so it MUST be set at
  # compile time here — setting it in runtime.exs aborts release boot with
  # `validate_compile_env`. `rewrite_on` trusts fly-proxy's
  # `x-forwarded-proto` (it terminates TLS and forwards plain HTTP), so real
  # requests get HSTS instead of a 301 loop; `exclude` lets the plain-HTTP
  # `/healthz` probe and localhost dev through without a redirect.
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: ["localhost", "127.0.0.1", {:paths, ["/healthz"]}]
  ]

# Configures Swoosh API Client
config :swoosh, :api_client, Emisar.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
