import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :emisar_web, EmisarWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force HTTPS in production (this also sets the HSTS header). Phoenix 1.8
  # reads `:force_ssl` via `Application.compile_env`, so it MUST be set at
  # compile time here — setting it in runtime.exs aborts release boot with
  # `validate_compile_env`. `rewrite_on` trusts fly-proxy's
  # `x-forwarded-proto` (it terminates TLS and forwards plain HTTP), so real
  # requests get HSTS instead of a 301 loop; `exclude` lets the plain-HTTP
  # `/healthz` probe, localhost dev, and the docker-compose hosts (`portal`,
  # where the e2e runners reach it over plain HTTP, and `host.docker.internal`,
  # the host-browser SSO entrypoint) through without a redirect. None of the
  # excluded hosts is ever a real prod request host (prod arrives as emisar.dev
  # via fly-proxy), so this is a dev-only accommodation.
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      "localhost",
      "127.0.0.1",
      "portal",
      "host.docker.internal",
      {:paths, ["/healthz"]}
    ],
    # Strong HSTS (Plug.SSL builds the Strict-Transport-Security header):
    # two-year max-age, every subdomain, and the `preload` directive so the
    # domain is eligible for the browsers' built-in preload list. Getting onto
    # that list is a one-time manual submission at hstspreload.org — the
    # directive just signals readiness; until you submit, this stays
    # reversible. `subdomains: true` assumes every *.emisar.dev is HTTPS-only.
    hsts: true,
    expires: 63_072_000,
    preload: true,
    subdomains: true
  ]

# Configures Swoosh API Client
config :swoosh, :api_client, Emisar.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
