import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# The docker-compose dev/e2e stack runs THIS prod release and reaches the portal
# over plain HTTP on internal hosts — the host browser via `localhost`, the e2e
# runners/mcp/seeder via the `portal` service name — so force_ssl must let those
# hosts through without a 301-to-HTTPS. Its image build sets
# EMISAR_DEV_HOST_EXCLUDES=1; a production build never does, so prod enforces HTTPS
# for EVERY request host and the config carries no dev-host TLS hole for a pentest
# to flag. Read at BUILD time — force_ssl is an `Application.compile_env`, so this
# env is consumed during `mix compile`/`mix release`, not at runtime.
dev_host_excludes =
  if System.get_env("EMISAR_DEV_HOST_EXCLUDES") == "1" do
    ["localhost", "127.0.0.1", "portal"]
  else
    []
  end

config :emisar_web, EmisarWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force HTTPS in production (this also sets the HSTS header). Phoenix 1.8
  # reads `:force_ssl` via `Application.compile_env`, so it MUST be set at
  # compile time here — setting it in runtime.exs aborts release boot with
  # `validate_compile_env`. `rewrite_on` trusts the GCP load balancer's
  # `x-forwarded-proto`, so real requests get HSTS
  # instead of a 301 loop; `exclude` always lets the plain-HTTP liveness and
  # readiness probes through, plus the dev-only hosts above only when this is
  # the docker build.
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: dev_host_excludes ++ [{:paths, ["/healthz", "/readyz"]}],
    # Strong HSTS (Plug.SSL builds the Strict-Transport-Security header):
    # two-year max-age, every subdomain, and the `preload` directive so the
    # domain is eligible for the browsers' built-in preload list. Getting onto
    # that list is a one-time manual submission at hstspreload.org — the
    # directive just signals readiness; until you submit, this stays
    # reversible. `subdomains: true` assumes every *.emisar.dev is HTTPS-only.
    hsts: true,
    expires: 63_072_000,
    preload: true,
    subdomains: true
  ]

# Dev-only routes (/dev/mailbox magic-link preview + /dev/dashboard) — compiled
# in ONLY when the docker-compose dev stack's build passes EMISAR_DEV_ROUTES=1.
# dev_routes is read via Application.compile_env in the router, so this is a
# BUILD-time decision; a production build never sets it, so prod never mounts
# /dev/*. The matching in-memory mailer is switched on at runtime (runtime.exs).
config :emisar_web, dev_routes: System.get_env("EMISAR_DEV_ROUTES") == "1"

# Configures Swoosh API Client
config :swoosh, :api_client, Emisar.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
